llm_providers:
  openai:
    models:
      - gpt-4o
      - o3-mini
      - o1-mini
      - gpt-4o-mini
      - gpt-4-turbo

  anthropic:
    models:
      - claude-3-5-haiku-latest
      - claude-3-5-sonnet-latest
      - claude-3-opus-20240229
      - claude-3-sonnet-20240229
      - claude-3-haiku-20240307

  gemini:
    models:
      - models/gemini-2.0-flash
      - models/gemini-2.0-flash-lite-preview-02-05
      - models/gemini-2.0-pro-exp-02-05
      - models/gemini-1.5-pro
      - models/gemini-1.5-flash

  aws:
    models:
      - us.amazon.nova-pro-v1:0
      - us.amazon.nova-lite-v1:0
      - us.amazon.nova-micro-v1:0
  groq:
    models:
      - llama-3.3-70b-versatile
      - llama-3.3-8b-instant
      - llama-3.2-3b-preview
      - mixtral-8x7b-32768

  sambanova:
    models:
      - Meta-Llama-3.1-405B-Instruct-16k
      - Meta-Llama-3.1-70B-Instruct-128k
      - Meta-Llama-3.1-8B-Instruct-16k
      - Meta-Llama-3.2-3B-Instruct

  deepseek:
    models:
      - deepseek-chat
      - deepseek-reasoner

  alibaba:
    models:
      - qwen-max
      - qwen-plus
      - qwen-turbo

